### ISSUE TITLE
Builds fails due to wrong resource file type

### ISSUE THREAD

**Issue by ghost** [VladThodo/behe-explorer#21]
A clean checkout of db4a9e3d09d39af7a22946031382c6f6b0ae0c39 / v1.0.0.3 does not build with gradle (2.10 by distributionUrl). Maybe AndroidStudio tries to cope with that, but it should be buildable without any graphical IDEs.

````
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeReleaseResources'.
> /home/krt/src/fdroiddata/build/com.vlath.beheexplorer/app/src/main/res/drawable/gear.ico: Error: The file name must end with .xml or .png

````

**Comment by VladThodo** [comment]
Hi krt16s!
Thank you for telling me that,I didn't know about this issue until now.
I will update the good source code as soon as I get home :) Until then,you could try to delete the gear.ico file,and see if something happens.

Thank you for getting involved!

**Comment by ghost** [comment]
Builds without it, but havent had the time to test if this will crash at runtime.

**Comment by VladThodo** [comment]
@krt16s  can you test if it builds now? I've updated the source code.
Thanks ;)

**Comment by ghost** [comment]
Errors now with

````
:app:processReleaseResources/home/krt/src/fdroiddata/build/com.vlath.beheexplorer/app/build/intermediates/res/merged/release/values-v24/values-v24.xml:3: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
````

**Comment by VladThodo** [comment]
Thanks for checking it :) I'll see what I can do about that,it seems pretty strange

**Comment by VladThodo** [comment]
Updated again.Does it build now?

**Comment by ghost** [comment]
Yep, works now. Thanks a lot :)
