### ISSUE TITLE
Crash when use voice button

### ISSUE THREAD

**Issue by xmikex7** [VladThodo/behe-explorer#31]
>Thank you for your feedback!Please add below details so that we can help you a bit faster.

When push voice button in address bar browser crashes.

### Agreements
>Please check the below checkboxes to make sure that you are not spamming

---

- [x] <b>I have read and accepted the [guidelines](https://github.com/VladThodo/behe-explorer/blob/development/CONTRIBUTING.md) for contributing to this project.</b>
- [ ] <b>I have checked the [open issues](https://github.com/VladThodo/behe-explorer/issues) and made shure that this is not a duplicate.</b>

---

### Short description
>Please add a short dscription of the issue.The description should contain:

---

 * BeHe ExloreR version: 2.0
 * Android version that you are using: 4.4 without Google services

---

### Reproduction
>Please tell us how to reproduce this issue.

Delete voice search engine and try push voice button in address bar

### Screenshots
>If you have any screenshots that can help please add them here 

---

**Comment by VladThodo** [comment]
Voice search on BeHe uses Google voice search engine to function.Having Android without Google Play services may cause this issue.
Anyway,voice search button is pretty useless,so it will be replaced with a refresh button ;)
Thank you for getting involved ;)

**Comment by VladThodo** [comment]
The voice search button has been replaced by a refresh button.I think we all agree that this issue should be closed
