### ISSUE TITLE
Don't downgrade versioncode

### ISSUE THREAD

**Issue by ghost** [VladThodo/behe-explorer#32]
You once again downgraded the versioncode, most likely you based the latest release of your maste rbranch instead of merging changes back from the development, where this was fixed in https://github.com/VladThodo/behe-explorer/commit/c1ff32aedef027bd1d19554d5fe50fd857605ad4.

**Comment by VladThodo** [comment]
Changed from `2051` to `20051`.I was in a hurry and I forgot to check the version code.
