### ISSUE TITLE
Search bar on the main screen doesn't work

### ISSUE THREAD

**Issue by CrimsonFork** [VladThodo/behe-explorer#37]
Android 5.1.1 22

**Comment by VladThodo** [comment]
Do you have JavaScript enabled? The search bar on the main screen needs JavaScript enabled in order to work.
Thank you for getting in touch :)

**Comment by CrimsonFork** [comment]
Oh... yes, it's off... :D

Am 1. Juni 2017 12:27:44 MESZ, schrieb Vlad Todosin <notifications@github.com>:
>Do you have JavaScript enabled? The search bar on the main screen needs
>JavaScript enabled in order to work.
>Thank you for getting in touch :)
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/VladThodo/behe-explorer/issues/37#issuecomment-305454087

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.
