### ISSUE TITLE
Copyright violation

### ISSUE THREAD

**Issue by Poussinou** [VladThodo/behe-explorer#45]
Hi @VladThodo 

I found [this app](https://play.google.com/store/apps/details?id=com.DarkGold.beheexplorer) on the Google Play Store. This guy just took your source code, added some ads in it and put it on the Store, without warning this is free software...

By the way, [all his apps are open source software he copied](https://play.google.com/store/apps/developer?id=Vu+Viet+My+Team)...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove the false app from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under Apache v2 license and this guy is violating it;
* He is falsely claiming he made the app;
* Provide some screenshots of your own app.

**Comment by VladThodo** [comment]
Thanks for letting me know. I wasn't aware of that, and never had to face such an obvious copyright violation as this. I'm surely going to open a request.

Also, thanks for your kind instructions, that's really helpful :-)

I'm glad to know I have people who are interested in my apps and are also ready to help.

**Comment by Poussinou** [comment]
No problem, you're welcome :)

Let me know if one day you find another copyright violation like this one, so that I can track the fake developer ;)

**Comment by jayaramanraj** [comment]
hi sir

**Comment by jayaramanraj** [comment]
help me sir

**Comment by Poussinou** [comment]
This fake dev is down now. Please let me know if you find any other new copy, so I can continue to track fake developers... Will close this issue for now, do not hesitate to reopen it ;)
