### ISSUE TITLE
Tabs ideas

### ISSUE THREAD

**Issue by VladThodo** [VladThodo/behe-explorer#9]
Hi folks,
I'm looking for implementing tabs in my browser,so I need some ideas for that.
Please respond to the following question:
1.Where the tabs should be located? (in the navigation drawer,or above the action bar,etc.)

**Comment by tobiasvandriessel** [comment]
I really like the navigation drawer idea, the way it's also implemented right now.

**Comment by VladThodo** [comment]
@tobiasvandriessel  Thanks for your ideea! Tabs will be added soon,but unfortunately not in the next version.. ;)

**Comment by VladThodo** [comment]
Tabs are located in thhe left navigation drawer and they work well.
This issue is CLOSED!
